Repository Arthur-Aillet/Cevy, pull requests merged in 2023-12, with the labels that each got.

#1 feat(ECS): Rtype Boostrap
  .gitignore
  CMakeLists.txt
  Makefile
  docs/Cevy.md
  docs/Cevy.uxf
  includes/test.hpp
  public/empty.hpp
  src/CMakeLists.txt
  src/entity.cpp
  src/entity.hpp
  src/game_engine/CMakeLists.txt
  src/game_engine/game_engine.cpp
  src/game_engine/game_engine.hpp
  src/game_engine/position.hpp
  src/game_engine/velocity.hpp
  src/registry.cpp
  src/registry.hpp
  src/sparse_array.cpp
  src/sparse_array.hpp
  src/test.cpp
  test/CMakeLists.txt
  test/unittest.cpp
  test/unittest_entity.cpp
  test/unittest_registery.cpp
  test/unittest_sparse_array.cpp
Labels: enhancement

#2 build: Fix clang tidy
  CMakeLists.txt
Labels: bug

#3 Scheduler
  src/App.cpp
  src/App.hpp
  src/CMakeLists.txt
  src/entity.hpp
  src/queries.hpp
  src/registry.cpp
  src/registry.hpp
Labels: enhancement

#9 doc: setup doxyfile with doxyfile awesome for styling
  .gitignore
  CMakeLists.txt
  Makefile
  TOOLS.md
  docs/bevy_icon.png
  docs/compare.md
  docs/doxygen/Doxyfile
  docs/doxygen/doxygen-awesome-css/doxygen-awesome-darkmode-toggle.js
  docs/doxygen/doxygen-awesome-css/doxygen-awesome-fragment-copy-button.js
  docs/doxygen/doxygen-awesome-css/doxygen-awesome-interactive-toc.js
  docs/doxygen/doxygen-awesome-css/doxygen-awesome-paragraph-link.js
  docs/doxygen/doxygen-awesome-css/doxygen-awesome-tabs.js
  docs/doxygen/doxygen-awesome-css/doxygen-awesome.css
  docs/doxygen/header.html
  src/App.hpp
Labels: documentation

#15 fix/feat: fix multiple crashes in schedule, added at start schedules
  Makefile
  src/ecs/App.hpp
  src/ecs/Schedule.cpp
  src/ecs/Schedule.hpp
Labels: bug, enhancement

#23 feat: converted is_super in is_world
  src/ecs/Schedule.hpp
  src/ecs/World.hpp
Labels: enhancement

#24 feat: add Query system
  src/ecs/CMakeLists.txt
  src/ecs/Query.hpp
  src/ecs/Schedule.hpp
  src/ecs/World.cpp
  src/ecs/World.hpp
Labels: enhancement

#28 feat: game engine overhaul upgrade
  src/ecs/App.hpp
  src/ecs/DefaultPlugin.cpp
  src/ecs/DefaultPlugin.hpp
  src/ecs/Entity.cpp
  src/ecs/Query.hpp
  src/ecs/Resource.hpp
  src/ecs/Time.cpp
  src/ecs/Time.hpp
  src/ecs/commands/EntityCommands.hpp
  src/engine/CMakeLists.txt
  src/engine/Camera.cpp
  src/engine/Camera.hpp
  src/engine/Engine.cpp
  src/engine/Position.hpp
  src/engine/Rotation.hpp
  src/engine/Vector.hpp
  src/engine/assets/AssetManager.cpp
  src/engine/assets/AssetManager.hpp
  src/engine/input.hpp
Labels: enhancement
